import Head from "next/head";
import React from "react";
import styles from "../../styles/Blogpost.module.css";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
const slug = () => {
  const [blog, setBlog] = useState({});
  const router = useRouter();
  const getBlog = async () => {
    const slug = router.query.slug;
    const d = await fetch(`http://localhost:3000/api/getblogs?slug=${slug}`);
    const data = await d.json();
    setBlog(data);
  };
  useEffect(() => {
    if (!router.isReady) return;
    getBlog();
  }, [router.isReady]);
  return (
    <div className={styles.container}>
      <Head>
        <title>{blog?.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>{blog?.title}</h1>
        <p>{blog?.content}</p>
      </main>
    </div>
  );
};
export default slug;
