import Head from 'next/head';
import React from 'react';
import styles from '../styles/Home.module.css';
const contact = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Contact Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <h1>Contact Us</h1>
        <p>
          Hi, I am a full stack developer and I am here to help you learn web
          development.
        </p>

      </div>
    </div>
  );
}

export default contact;
