import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ allblogs }) {
  console.log(allblogs);
  return (
    <>
      <Head>
        <title>Hunting Coders</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.headcnt}>
          <h1 className={inter.className}>Hunting Coders</h1>
          <Image
            src="/logo.jpg"
            alt="Picture of the Logo"
            width={335}
            height={251}
          />
          <p className={inter.className}>
            A blog for hunting coders by hunting coder
          </p>
        </div>
        <h2 className={inter.className}>Popular Blogs</h2>
        <div className={styles.grid}>
          {allblogs?.slice(0, 4).map((e, i) => (
            <div key={i} className={styles.card}>
              <Link href={`/blogpost/${e.slug}`} className={inter.className}>
                {e.title}
              </Link>
              <p className={inter.className}>{e.content.slice(0, 55)}...</p>
            </div>
          ))}
        </div>
      </main>
    </>
  );
}
export async function getServerSideProps(context) {
  const d = await fetch("http://localhost:3000/api/blogs?count=4");
  const data = await d.json();
  console.log(data);
  return {
    props: { allblogs:data.files },
  };
}
